### ISSUE TITLE
Multiple attachments ended with statusCode 504

### ISSUE THREAD

**Issue by jprecuch** [MeilCli/slack-upload-file#1088]
## Description
[Please easy english or easy japanese]
```
      - name: Send logs to Slack thread
        if: fromJSON(vars[inputs.configuration_json_variable]).slack_notifications && always()
        uses: MeilCli/slack-upload-file@0dae709585570d7a184ebea7221d7fd8f8ceab60 # v4.0.12
        with:
          slack_token: ${{ secrets.SLACK_APP_TOKEN }}
          channel_id: ${{ fromJSON(vars[inputs.configuration_json_variable]).slack_notifications_channel }}
          file_path: 'report-*/*'
          initial_comment: "Here are attached logs from workflow"
          thread_ts: ${{ steps.slack-notifications.outputs.thread_ts }}
          file_type: text
          file_name: ${{ github.run_id }}
          title: ${{ github.run_id }}
```
Ends with:
```
/usr/bin/docker exec  1ba6a7802f58e2e647682d220f8bbebac6006bd3ea96377edfb616c5153be8e6 sh -c "cat /etc/*release | grep ^ID"
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 504
Error: An API error occurred: internal_error
```
I've tried to upload about 15 files to Slack. Is there some limit or possibility to have better check for size/allowance for Slack?
