### ISSUE TITLE
Importing a junit.xml

### ISSUE THREAD

**Issue by rcubillo** [MeilCli/slack-upload-file#345]
Hi, I have a github action thats is generating a xml report. The github runner is storing that xml. 
I'm running a CLI command to generate the report using NPM. . You can see it here:

```
Run `npm audit` for details.
Starting Testim.io CLI
JUnit XML file saved to /home/runner/junit.xml
```

 I want to import it into slack but it's not working. Do you have any idea on what's the best way to do it? 

This is what I have:

```
    - uses: MeilCli/slack-upload-file@v1.4.11
      id: message
      with:
          slack_token: "${{secrets.SLACK_BOT_TOKEN}}"
          channels: "${{secrets.SLACK_QA_CHANNEL_ID}}"
          file_path: "/home/runner"
          file_name: "junit"
          file_type: 'xml'
          initial_comment: 'post by slack-upload-file'
```
