### ISSUE TITLE
file_path and file_name as a value of environmental variable

### ISSUE THREAD

**Issue by aholovenko** [MeilCli/slack-upload-file#449]
Is it possible to assign the file_path and file_name of the file to the env variable?
e.g.
```
        uses: MeilCli/slack-upload-file@v1
        env:
          FILE_NAME: ${{ steps.step2.outputs.FILE_NAME }}
        with:
          slack_token: XXXX
          channels: XXXX
          file_path: ./${{FILE_NAME}}
          file_name: ./${{FILE_NAME}}
          file_type: 'text'
          initial_comment: 'Sharing file:'
```

Currently, I am getting error:
```
The workflow is not valid. .github/helloworld.yml (Line: X, Col: Y): Unrecognized named-value: 'FILE_NAME'. Located at position 1 within expression: FILE_NAME .github/helloworld.yml (Line: X, Col: Y): Unrecognized named-value: 'FILE_NAME'. Located at position 1 within expression: DIFF_NAME
```

**Comment by MeilCli** [comment]
@aholovenko 
I think in your case, you no need to use environment variable.

```yml
uses: ....
with:
  file_path: ${{'./'}}${{steps.step2.outputs.FILE_NAME}}
  file_name: ${{'./'}}${{steps.step2.outputs.FILE_NAME}}
```
