### ISSUE TITLE
How to use wildcards for the file to download

### ISSUE THREAD

**Issue by cb-anomitromunshi** [MeilCli/slack-upload-file#529]
hi,
```
- name: Upload artifacts to slack
      uses: MeilCli/slack-upload-file@v2
      with: 
        slack_token: ${{ secrets.SLACK_TOKEN }}
        file_path: 'src/main/resources/master*.txt'
        file_type: 'text'
        channels: testchannelprism
        initial_comment: 'post by slack-upload-file'
```
      As of now i tried by providing * in filepath, but no luck can u help pls
