### ISSUE TITLE
Error: An API error occurred: missing_scope

### ISSUE THREAD

**Issue by teodorpatras** [MeilCli/slack-upload-file#665]
## Description

Hi, when trying to upload a png file to a slack channel where the bot is member of, I get `Error: An API error occurred: missing_scope`. I have added the following Bot Token Scopes:

`chat:write`, `files:read` and `files:write`

This is how I use it:

```
      - name: Upload screenshots to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL }}
          file_path: 'output/selenium-screenshot-1.png'
          initial_comment: 'Some tests have failed:'
```

Am I missing other scopes the bot needs?

## Environment

`MeilCli/slack-upload-file@v3`
