### ISSUE TITLE
Cannot read properties of undefined on latest release

### ISSUE THREAD

**Issue by jprecuch** [MeilCli/slack-upload-file#856]
[Please easy english or easy japanese]

## Description
After new release, following error happens in our pipelines
```
Run MeilCli/slack-upload-file@v3
/usr/bin/docker exec  c85ff6f7f1bc0117e3eee4598cae8d07550def6c0f4edef206e3d3e1bc7085fa sh -c "cat /etc/*release | grep ^ID"
Error: Cannot read properties of undefined (reading 'id')
```
## Environment
```
      - name: Send debug logs to a Slack thread
        if: inputs.slack-notifications && always()
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_APP_TOKEN }}
          channel_id: ${{ inputs.slack-notifications-channel }}
          file_path: ${{ env.DEBUG_LOGS_FILE }}
          initial_comment: ${{ github.event.action }}
          thread_ts: ${{ steps.slack-notifications.outputs.thread_ts }}
          file_type: text
          file_name: ${{ github.run_id }}
          title: ${{ github.run_id }}
```
