### ISSUE TITLE
An API error occurred: internal_error

### ISSUE THREAD

**Issue by mabdelhafiz94** [MeilCli/slack-upload-file#870]
## Description

Logs:
```
Run MeilCli/slack-upload-file@v3
  with:
    slack_token: ***
    channel_id: C052NECDLD8
    file_path: ./app/build/outputs/apk/staging/app-staging.apk
    file_type: apk
    initial_comment: A new testing APK has been generated!
    file_path_follow_symbolic_links: true
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.21-9/x64
Error: An API error occurred: internal_error
```

YAML

```
- name: Upload APK to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: 'C052NECDLD8'
          file_path: './app/build/outputs/apk/staging/app-staging.apk'
          file_type: 'apk'
          initial_comment: 'A new testing APK has been generated!'
```
